## Instituto Federal da Paraíba 
Rafael Figueredo Guimarães  
Engenharia de Computação  
Métodos Numéricos - Exercício 2 - Numpy

In [59]:
import numpy as np

**Exercise 1: Existem outras formas de fazer essa importação? Liste-as e discuta suas vantagens e desvantagens.**

1. R: 
~~~ python  
import numpy  # importa o modulo 
import numpy as np # importa o modulo atribuíndo um apelido ao mesmo
from numpy import array # importa apenas uma função do modulo
from numpy import * # importa todas as funções do modulo
~~~

A principal diferença está em como os métodos serão chamados. 

1. caso
~~~ python  
numpy.array
~~~
2. caso: 
~~~ python  
np.array
~~~
3. caso: 
~~~ python  
array
~~~
4. caso: 
~~~ python  
array
~~~

Os casos 3 e 4 não são interessantes quando usamos mais de uma biblioteca, uma vez que, os nomes dos metodos podem ser iguas com funções e argumentos diferentes. 

In [60]:
arr = np.array([-2, 4.3, 7, 9]) 

my_tuple = (8, -5, 0, 3.2)
arr2 = np.array(my_tuple)

print('arr = ', arr) 
print('arr2 = ', arr2)

arr =  [-2.   4.3  7.   9. ]
arr2 =  [ 8.  -5.   0.   3.2]


**Exercise 2 Explique os resultados das execuções de todas as células do tutorial, com suas palavras, logo após cada resultado.**

2. Todos os valores foram forçados em tipo float, porque só podemos ter um tipo nos valores da estrutura array em ambas as saídas

In [61]:
arr = np.array([-2, 4.3, 7, 9, 'string']) 

my_tuple = (8, -5, 0, 3.2)
arr2 = np.array(my_tuple)

print('arr = ', arr) 
print('arr2 = ', arr2)

arr =  ['-2' '4.3' '7' '9' 'string']
arr2 =  [ 8.  -5.   0.   3.2]


**Exercise 3
É curioso notar que todos os elementos de arr se tornaram float após a criação do array, mesmo que nem todos os elementos da lista fossem desse tipo. Por que isso ocorreu? E se um desses elementos fosse um string, qual seria a saída?**

3. É feito um casting em todos os valores para o tipo string, particularmente faz muito sentido, já que não haveria como representar strings numericamente. 

In [62]:
arr = np.arange(10)
print(arr, '\n')

arr2 = np.arange(1, 32, 2).reshape(4, 4) # reshape muda o formato da array - nesse caso de (16) para (4x4)
print(arr2)

[0 1 2 3 4 5 6 7 8 9] 

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]


In [63]:
np.arange(1,100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [64]:
# Método linspace()

arr = np.linspace(1, 100, 10) # de 1 a 100, contendo 10 valores
print(arr, '\n')

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.] 



**Exercise 4 Quais as diferenças entre os métodos arange e linspace para criar arrays?**

4. De acordo com a Documentação Do Numpy, a função **arange** cria um arranjo contendo uma seqüência de valores especificados em um intervalo com início e fim dados, espaçados de maneira uniforme. Já função **linspace** cria uma seqüência de números uniformemente espaçados entre os limites dados

In [65]:
# Array vazia com o método empty()

arr2 = np.empty((6,4)) # normalmente a saída é lixo de memória ou zeros
print(arr2, '\n')


# Np.Eye

arr3 = np.eye(4) # eye cria uma array de duas dimensões com 1 na da diagnoal e 0 nos outros elementos
print(arr3)
len(arr2)

[[6.93793202e-310 4.68175079e-310 4.68174878e-310 6.93793223e-310]
 [6.93793224e-310 6.93793220e-310 6.93792829e-310 6.93792829e-310]
 [6.93793224e-310 6.93792829e-310 6.93792829e-310 4.68174878e-310]
 [6.93793055e-310 6.93793219e-310 6.93792973e-310 6.93792829e-310]
 [6.93793221e-310 6.93793223e-310 6.93793223e-310 6.93793055e-310]
 [6.93793055e-310 6.93793219e-310 6.93792829e-310 6.93793055e-310]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


6

In [66]:
arr = np.zeros(8) # array contendo 8 'zeros'
print (arr, '\n')

arr2 = np.ones((4,3)) # array contendo 12 'uns', no formato 4 x 3
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0.] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [67]:
arr = np.linspace(.5, 50, 10)

print(arr, '\n')

print('.shape: ', arr.shape)    # imprime o formato da array
print('.size: ', arr.size)      # imprime o tamanho da array
print('.dtype: ', arr.dtype)    # imprime o tipo de dado dos elementos

[ 0.5  6.  11.5 17.  22.5 28.  33.5 39.  44.5 50. ] 

.shape:  (10,)
.size:  10
.dtype:  float64


In [68]:
print('.ndim: ', arr.ndim)          # número de dimensões
print('.itemsize: ', arr.size)      # tamanho de cada elemento em bytes

.ndim:  1
.itemsize:  10


**Exercise 5 O método len() é usado para mostrar o tamanho de uma lista. Esse método também funciona para arrays? Explique.**

5. A função **len()** devolve a quantidade de linhas (ou subvetores) contidos na estrutura array, nesse caso, não é efiente quando se busca a quantidade de elementos unicos na estrutura

In [69]:
arr2 = np.ones((4,3)) # array contendo 12 'uns', no formato 4 x 3
print(arr2)

len(arr2)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4

In [70]:
arr = np.arange(1,10)
print('array original: ', arr, '\n')

# Como já vimos 'reshape()' muda o formato da array, MAS o número de elementos dos dois formatos tem que coincidir, exemplo:
arr2 = arr.reshape((3,3))
print ('formato 3x3: \n', arr2, '\n')

array original:  [1 2 3 4 5 6 7 8 9] 

formato 3x3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [71]:
arr.max() # retorna o valor máximo

9

In [72]:
print(arr.argmax()) # retorna o índice que contém o valor máximo
arr[8] == arr[arr.argmax()]

8


True

In [73]:
arr.min() # retorna o mínimo

1

In [74]:
arr.mean() # retorna a média

5.0

In [75]:
arr.std() # retorna o desvio padrão

2.581988897471611

In [76]:
arr.sum() #retorna a soma de todos os elementos da array

45

In [77]:
### FUNÇÕES UNIVERSAIS ###

np.sqrt(arr) # retorna um array com a raiz quadrada de cada elemento

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [78]:
np.sin(arr) # retorna um array com o seno de cada elemento

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [79]:
np.cos(arr) # retorna um array com o cosseno de cada elemento

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [80]:
np.exp(arr) # retorna um array com o exponencial cada elemento (e^x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [81]:
# vamos criar as arrays A e B para fazer operações com elas

A = np.arange(10)
B = np.arange(10,38,3)

print (' A: ', A, '\n', 'B: ', B)

 A:  [0 1 2 3 4 5 6 7 8 9] 
 B:  [10 13 16 19 22 25 28 31 34 37]


In [85]:
somar = A + B
subtrair = A - B
dividir = A / B
multiplicar = A * B

print('somar: ', somar)
print('subtrair: ', subtrair )
print('dividir: ', dividir)
print('multiplicar: ', multiplicar)

somar:  [10 14 18 22 26 30 34 38 42 46]
subtrair:  [-10 -12 -14 -16 -18 -20 -22 -24 -26 -28]
dividir:  [0.         0.07692308 0.125      0.15789474 0.18181818 0.2
 0.21428571 0.22580645 0.23529412 0.24324324]
multiplicar:  [  0  13  32  57  88 125 168 217 272 333]


~~~ python 
B/A     # a array A contém um zero como primeiro elemento
~~~

In [87]:
''' Você pode fazer operações envolvendo arrays e um único elemento, dessa forma numpy itera a operação 
do elemento único com todos os componentes da array, exemplo: ''' 

A * 100    # retorna um array com a multiplicação de todos elementos da array por 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

**Exercise 6 Explique, com suas palavras, o conceito de vetorização do numpy.**

6. Numpy é uma exelente ferramenta para desenvolvimento de projetos que envolvem vetores e matrizes (vetores N-dimencionais) com todo um suporte matemático disponibilizado em métodos.  

In [90]:
# criar uma array com o quadrado dos números de 1 a 10
arr = np.arange(1, 10) **2
arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [91]:
# acessando o primeiro elemento
print('1º elemento: ', arr[0])    # lembrar que índice começa do 0

# acessando o quinto elemento
print ('5º elemento: ', arr[4])   # O quinto elemento é acessado pelo índice 4

1º elemento:  1
5º elemento:  25


In [92]:
# Em um array de duas dimensões (ou mais) existem duas formas de acessar o índice:

arr = arr.reshape((3,3))
print (arr, '\n')

# Usando colchetes duplos [][]
print ('Acessando o elemento 25: ', arr[1][1])

# Ou minha preferência pessoal - separando índices por vírgula
print ('Acessando o elemento 25: ', arr[1,1])

# acessando o último elemento usando o -1
arr[-1, -1] 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

Acessando o elemento 25:  25
Acessando o elemento 25:  25


81

In [93]:
# Para acessar fatias de elementos, usamos o slice [i:i], exemplo

# linha: acessar da linha de índice 0 a linha de índice 2 (excluindo esta) = [0:2]
# coluna: acessar da coluna de índice 0 a coluna de 3 (excluindo esta) = [0:3] - no nosso caso, todas as colunas
print(arr[0:2 , 0:3],'\n')

# outra forma de obter o mesmo resultado é usando [:], que pega todos os elementos
print(arr[0:2 , 0:3])

[[ 1  4  9]
 [16 25 36]] 

[[ 1  4  9]
 [16 25 36]]


In [94]:
# Podemos criar uma nova array com slice de outra

arr2 = arr[ : , 1:3]
arr2

array([[ 4,  9],
       [25, 36],
       [64, 81]])

In [95]:
# Podemor atribuir novos elementos a nossa array, usando slice

arr[1:2, :] = -99
arr

array([[  1,   4,   9],
       [-99, -99, -99],
       [ 49,  64,  81]])

In [96]:
A = np.arange(10)
print ('A: ', A)

A:  [0 1 2 3 4 5 6 7 8 9]


In [97]:
A > 5 # retorna uma array de variáveis booleanas de acordo com a condição

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [98]:
# Também odemos criar uma array a partir dessa condição
B = A > 5

In [99]:
print (A [A > 5])

print (A [B])

[6 7 8 9]
[6 7 8 9]
