## Federal Institute of Paraiba - IFPB
Rafael Figueredo Guimarães  
Computer Engeneering  
Numerical Methods - Exercises 3 - Numpy

**1. Import the numpy package under the name np**

In [49]:
import numpy as np

**2. Print the numpy version and the configuration**

In [50]:
np.__version__, np.show_config

('1.16.4', <function numpy.__config__.show()>)

**3. Create a null vector of size 10**

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**4. How to find the memory size of any array**

In [52]:
a = np.zeros(10)
print(np.size(a)) # Quantidade de elementos no array
print(a.itemsize) # tamanho de um elemento do array em bytes

10
8


**5. How to get the documentation of the numpy add function from the command line?**

In [53]:
np.info(a)

class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x55e2430e1e80
byteorder:  little
byteswap:  False
type: float64


**6. Create a null vector of size 10 but the fifth value which is 1**

In [54]:
b = np.zeros(10)
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**7. Create a vector with values ranging from 10 to 49**

In [55]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**8. Reverse a vector (first element becomes last)**

In [56]:
c = np.arange(11)
print(c)
print(c[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


**9. Create a 3x3 matrix with values ranging from 0 to 8**

In [57]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**10. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [58]:
d = np.array([1,2,0,0,4,0])
np.nonzero(d) 

(array([0, 1, 4]),)

**11. Create a 3x3 identity matrix**

In [59]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**12. Create a 3x3x3 array with random values**

In [60]:
np.random.random_sample((3,3,3), )

array([[[0.40210046, 0.62391934, 0.96739995],
        [0.67449389, 0.24278975, 0.19961134],
        [0.11814429, 0.6921081 , 0.86477894]],

       [[0.56725207, 0.35134224, 0.52418383],
        [0.18141526, 0.74359525, 0.78355717],
        [0.47185327, 0.03500381, 0.91314206]],

       [[0.65092001, 0.11683432, 0.06087133],
        [0.27603507, 0.16977621, 0.25813065],
        [0.01301534, 0.7553366 , 0.84649906]]])

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [61]:
i = np.arange(100).reshape(10,10)

In [62]:
i.max(), i.min()

(99, 0)

**14. Create a random vector of size 30 and find the mean value**

In [63]:
j = np.arange(1, 30)

In [64]:
j.mean()

15.0

**15. Create a 2d array with 1 on the border and 0 inside (★☆☆)**

In [65]:
h = np.ones(9, dtype = 'int').reshape(3,3)

In [66]:
h[1:-1, 1:-1] = 0
h

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

**16. How to add a border (filled with 0's) around an existing array? (★☆☆)**

In [67]:
def pad_with(vector, pad_width, iaxis, kwargs):
...     pad_value = kwargs.get('padder', 10)
...     vector[:pad_width[0]] = pad_value
...     vector[-pad_width[1]:] = pad_value
...     return vector
np.pad(h, 1, pad_with, padder = 0)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

**17. What is the result of the following expression? (★☆☆)**

In [68]:
0 * np.nan # Nan
np.nan == np.nan # True
np.inf > np.nan # False
np.nan - np.nan # nan
np.nan in set([np.nan]) #True
0.3 == 3 * 0.1 # False

False

**18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)**

In [69]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

**19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)**

In [70]:
k = np.zeros((8,8),dtype=int)
k[1::2,::2] = 1
k[::2,1::2] = 1
k

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?**

In [71]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

**21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)**

In [72]:
X = np.tile(np.array([[0,1],[1,0]]), (4,4))
X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**22. Normalize a 5x5 random matrix (★☆☆)**

In [73]:
Z = np.random.random((5,5))
print(Z)
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[0.18129258 0.9215171  0.14767178 0.42667856 0.34293406]
 [0.07336838 0.56649851 0.34931005 0.46705864 0.22001935]
 [0.57927085 0.54786528 0.42217065 0.42809655 0.27607149]
 [0.46959136 0.05845764 0.85769959 0.82732343 0.31596975]
 [0.80514082 0.12968978 0.0569189  0.77305422 0.89880078]]
[[-0.97374557  1.75232619 -1.097563   -0.07004705 -0.37845822]
 [-1.37120487  0.44487673 -0.35497699  0.07866321 -0.83112403]
 [ 0.49191426  0.37625495 -0.08664862 -0.06482494 -0.62469727]
 [ 0.08799064 -1.42611758  1.51730141  1.40543321 -0.47776143]
 [ 1.32373989 -1.16378648 -1.43178439  1.20557256  1.66866737]]


**23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)**

In [74]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


**24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)**

In [75]:
a = np.arange(15,  dtype='int').reshape(5,3)
b = np.arange(6,  dtype='int').reshape(3,2)
print("A: \n", a)
print("\nB: \n", b)
print("\nA*B: \n", np.dot(a,b))

A: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

B: 
 [[0 1]
 [2 3]
 [4 5]]

A*B: 
 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


**25. Given a 1D array, negate all elements which are between 3 and 8, in place.**

In [76]:
X = np.arange(10)
X[4:8:] *= -1
print(X)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


**26. What is the output of the following script? (★☆☆)**

In [77]:
print(sum(range(5),-1)) # a função sum é definida na prṕria liguagem python
from numpy import * # nesse import a função sum é sobreposta
print(sum(range(5),-1))

10
10


In [78]:
import numpy as np

**27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)**

In [79]:
Z = np.arange(5, dtype='int')
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z


[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


**28. What are the result of the following expressions?**

In [80]:
print(np.array(0))
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


0
nan
0
[-9.22337204e+18]


/home/rafaelfigueredog/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/home/rafaelfigueredog/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


- Essa mensagem de erro é referente a tentativa de casting do 'np.nan' que não é numérico para um tipo int ou float 

**29. How to round away from zero a float array ?**

In [81]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.trunc(Z + np.copysign(0.5, Z)))

[ 3.43752957  4.41375385 -3.08619417  0.09846916  6.3007182  -4.76821939
  5.54498809 -5.67689157  0.42516217  5.54680538]
[ 3.  4. -3.  0.  6. -5.  6. -6.  0.  6.]


**30. How to find common values between two arrays?**

In [82]:
a = np.arange(1, 11)
b = np.arange(5, 16)
np.intersect1d(a, b)

array([ 5,  6,  7,  8,  9, 10])

**31. How to ignore all numpy warnings (not recommended)? (★☆☆)**


In [83]:
defaults = np.seterr(all="ignore")
print(np.array([np.nan]).astype(int).astype(float))

#voltando
_ = np.seterr(**defaults)

[-9.22337204e+18]


**32. Is the following expressions true? (★☆☆)**

In [84]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1)) 

False
1j
nan


/home/rafaelfigueredog/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
/home/rafaelfigueredog/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


~~~ python
np.sqrt() ~~~
- An array of the same shape as x, containing the **positive** square-root of each element in x.


**33. How to get the dates of yesterday, today and tomorrow?**

In [85]:
today = np.datetime64('today', 'D')
yesterday = today - 1
tomorow = today + 1
print(yesterday)
print(today)
print(tomorow) # awsome!

2019-08-17
2019-08-18
2019-08-19


**34. How to get all the dates corresponding to the month of July 2016? (★★☆)**

In [86]:
np.arange('2016-06', '2016-07',  dtype='datetime64[D]')

array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29', '2016-06-30'], dtype='datetime64[D]')

**35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)**

In [87]:
A = np.ones(3)*1
print(A)
B = np.ones(3)*2
print(B)
C = np.ones(3)*3
print(C)
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


**36. Extract the integer part of a random array using 5 different methods (★★☆)**

In [88]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 3. 6. 3. 5. 8. 6. 0. 4. 6.]
[2. 3. 6. 3. 5. 8. 6. 0. 4. 6.]
[2. 3. 6. 3. 5. 8. 6. 0. 4. 6.]
[2 3 6 3 5 8 6 0 4 6]
[2. 3. 6. 3. 5. 8. 6. 0. 4. 6.]


**37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)**

In [89]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)**

In [90]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


**39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)**

In [91]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

**40. Create a random vector of size 10 and sort it (★★☆)**

In [92]:
a = np.random.random(10)
print(a, "\n")
a.sort()
print(a)

[0.78351745 0.49706919 0.59959854 0.09259557 0.56659714 0.88645044
 0.59880857 0.88112347 0.16922399 0.19416212] 

[0.09259557 0.16922399 0.19416212 0.49706919 0.56659714 0.59880857
 0.59959854 0.78351745 0.88112347 0.88645044]


**41. How to sum a small array faster than np.sum? (★★☆)**

In [93]:
a = np.arange(4)
np.add.reduce(a)

6

**42. Consider two random array A and B, check if they are equal (★★☆)**

In [94]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

#possui uma tolerancia relacionada aos valores
equal = np.allclose(a,b)
print(equal)

#não possui tolerancia, ambos os arrays devem ser exatamente iguais
equal = np.array_equal(a,b)
print(equal)

False
False


**43. Make an array immutable (read-only) (★★☆)**

In [95]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: assignment destination is read-only

- Mensagem de erro relativo a tentativa de mudança de um array somente leitura

**44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)**

In [ ]:
Z = np.random.random((10,2))

X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)

**45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)**

In [ ]:
a = np.random.random(10)

print(a)

print(a.argmax()) # returns the index of the max

a[a.argmax()] = 0

print(a)



**46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)**

In [ ]:
a = np.zeros((5,5), [('x',float),('y',float)])

a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),

np.linspace(0,1,5))

print(a)

**47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))**

In [ ]:
X = np.arange(8)

Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)

print(np.linalg.det(C))

**48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)**

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:

    print(np.iinfo(dtype).min)

    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:

    print(np.finfo(dtype).min)

    print(np.finfo(dtype).max)

    print(np.finfo(dtype).eps)

**49. How to print all the values of an array? (★★☆)**

In [ ]:
np.set_printoptions(threshold=np.nan)

**50. How to find the closest value (to a given scalar) in a vector? (★★☆)**

In [ ]:
x = np.arange(100)
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

**51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)**

In [97]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


**52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)**

In [99]:
Z = np.random.random((10,2))
print(Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.5211936  0.8802748 ]
 [0.93251713 0.06097919]
 [0.08758795 0.08539335]
 [0.50392015 0.10186086]
 [0.11496348 0.21727966]
 [0.0017946  0.23985687]
 [0.49029704 0.18316456]
 [0.63595036 0.87324897]
 [0.92845387 0.68271644]
 [0.97332939 0.07350311]]
[[0.         0.91675096 0.9054559  0.77860557 0.77755094 0.82456682
  0.69779459 0.11497163 0.45264802 0.92482827]
 [0.91675096 0.         0.84528183 0.43054231 0.83236038 0.94775612
  0.45878958 0.86471616 0.62175053 0.04269062]
 [0.9054559  0.84528183 0.         0.41665775 0.13469751 0.17669035
  0.41440779 0.95990511 1.03143123 0.88582125]
 [0.77860557 0.43054231 0.41665775 0.         0.40572009 0.52074271
  0.08243713 0.78260564 0.71945958 0.47026503]
 [0.77755094 0.83236038 0.13469751 0.40572009 0.         0.11539899
  0.37688077 0.83768912 0.9372289  0.87032392]
 [0.82456682 0.94775612 0.17669035 0.52074271 0.11539899 0.
  0.4917811  0.89629185 1.02704528 0.9856741 ]
 [0.69779459 0.45878958 0.41440779 0.08243713 0.37688077 0.4917811


**53. How to convert a float (32 bits) array into an integer (32 bits) in place?**

In [100]:
A = np.arange(10, dtype=np.float32)
A = A.astype(np.int32, copy=False)
print(A)

[0 1 2 3 4 5 6 7 8 9]


**54. How to read the following file? (★★☆)**

In [101]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  , 0 , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


**55. What is the equivalent of enumerate for numpy arrays? (★★☆)**

In [102]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


**56. Generate a generic 2D Gaussian-like array (★★☆)**

In [103]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
A = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(A)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

**57. How to randomly place p elements in a 2D array? (★★☆)**

In [108]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**58. Subtract the mean of each row of a matrix (★★☆)**

In [109]:
# Author: Warren Weckesser
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.24337024  0.08658608 -0.19487214 -0.14646048 -0.06207559  0.08200847
  -0.1633861  -0.02966519  0.02422171  0.16027301]
 [-0.23432988  0.56049041 -0.08721276 -0.3031199   0.39785016 -0.21299616
  -0.25717298 -0.01528044  0.03039868  0.12137288]
 [-0.34439707 -0.09106006  0.18801212 -0.40423806  0.15813737  0.18755303
   0.32656944  0.44599255 -0.02152281 -0.44504651]
 [ 0.26432367  0.31800639 -0.21192299  0.2996088   0.41815893 -0.26838342
   0.14323937 -0.31881037 -0.28290082 -0.36131956]
 [ 0.23895925 -0.13125514 -0.32937954  0.49049069 -0.40020705 -0.28110642
   0.49453182 -0.242604    0.39213082 -0.23156042]]


**59. How to sort an array by the nth column? (★★☆)**

**60. How to tell if a given 2D array has null columns? (★★☆)**

**61. Find the nearest value from a given value in an array (★★☆)**

**62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)**

**63. Create an array class that has a name attribute (★★☆)**

**64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated
indices)? (★★★)**

**65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)**

In [113]:
X = [1,1,1,1,1,1]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(X)
print(I)
print(F)

[1, 1, 1, 1, 1, 1]
[1, 3, 9, 3, 4, 1]
[0. 2. 0. 2. 1. 0. 0. 0. 0. 1.]


**66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)**

In [114]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


**67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)**

In [116]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[52 46 56 73]
 [64 50 58 58]
 [54 35 69 49]]
[[52 46 56 73]
 [64 50 58 58]
 [54 35 69 49]]


**68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size
describing subset indices? (★★★)**

In [117]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.40302176 0.69616172 0.45640509 0.57182783 0.53087413 0.61264697
 0.65688593 0.45381572 0.56745847 0.41125589]
0    0.403022
1    0.696162
2    0.456405
3    0.571828
4    0.530874
5    0.612647
6    0.656886
7    0.453816
8    0.567458
9    0.411256
dtype: float64


**69. How to get the diagonal of a dot product? (★★★)**

In [120]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

  
print(np.diag(np.dot(A, B)))

print(np.sum(A * B.T, axis=1))

np.einsum("ij,ji->i", A, B)

[2.19691393 2.07680592 1.54506031 1.18594273 0.55942215]
[2.19691393 2.07680592 1.54506031 1.18594273 0.55942215]


array([2.19691393, 2.07680592, 1.54506031, 1.18594273, 0.55942215])

**70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each
value? (★★★)**

In [124]:
a = np.array([1,2,3,4,5])

a0 = np.zeros(len(a) + (len(a)-1)*(3))
a0[::3+1] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


**71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)**

In [127]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**72. How to swap two rows of an array? (★★★)**

In [128]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments
composing all the triangles (★★★)**

In [129]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 81) ( 3, 83) ( 5, 10) ( 5, 21) ( 6, 11) ( 6, 54) (10, 21) (11, 54)
 (14, 61) (14, 95) (20, 37) (20, 93) (21, 31) (21, 45) (21, 51) (21, 85)
 (31, 45) (37, 93) (49, 77) (49, 95) (50, 54) (50, 59) (51, 85) (54, 59)
 (61, 95) (77, 95) (79, 92) (79, 95) (81, 83) (92, 95)]


**74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)**

In [130]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


**75. How to compute averages using a sliding window over an array? (★★★)**

In [131]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


**76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each
subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)**

In [132]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


**77. How to negate a boolean, or to change the sign of a float inplace? (★★★)**

In [134]:
a = np.random.randint(0,2,100)
print(np.logical_not(a, out=a))

a = np.random.uniform(-1.0,1.0,100)
print(np.negative(a, out=a))

[0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0
 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0 1 1 0 1
 1 1 0 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 0 1 1 1]
[ 0.08399341  0.81825561 -0.91859756 -0.66715351  0.71687658  0.55285726
  0.12657668  0.30053194  0.9405915  -0.28399728 -0.23558167  0.91691959
  0.4072017  -0.56958917 -0.30620856 -0.11957352 -0.7650597  -0.16457461
  0.75776288  0.17259357  0.35468991  0.57393698  0.53726255  0.50233672
 -0.36357376  0.1041202   0.55060132  0.27869167 -0.16762637  0.33810202
  0.16297983 -0.25087116 -0.32923508 -0.27294416  0.06709891  0.43821603
  0.80264303 -0.31607715  0.31765199  0.49156677  0.3017106  -0.78054092
  0.93050334 -0.90894908  0.8673548  -0.54969723  0.17704967  0.51702886
  0.89536747  0.6818775  -0.69243014 -0.11659174  0.11689331  0.02371255
  0.73317714  0.73779096  0.18433655 -0.67445366 -0.46007534 -0.48116514
 -0.89862743  0.77268088  0.67682198  0.30060079  0.46214244 -0.26

**78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i
(P0[i],P1[i])? (★★★)**

In [135]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[11.48453236  0.77352209  6.38277683 10.24931482  0.67761418  9.91685692
  6.29492343  6.11980283  1.85623559  3.39798026]


**79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each
point j (P[j]) to each line i (P0[i],P1[i])? (★★★)**

In [136]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.12991653  0.0579515   2.18976889  0.56805037 12.12242819  0.5790064
   5.22736883  2.89730297  7.01874712  8.71764216]
 [ 6.47963221  1.56191821  5.90143509  3.64931316  8.86974834  2.0821074
   4.11095057  7.23660222  9.63668401  5.88469563]
 [13.65884211  6.54064567 10.54368133 11.09073353  1.93008886  6.89890965
   0.15417249 13.98314626 11.81477118  0.61915153]
 [ 0.50142486  1.90156194  1.94777225  2.50640286 12.08668379  2.64843612
   2.8136621   0.25753875  2.70256588  8.10031551]
 [ 7.93600523 13.93807499  0.4734901   7.52891263  0.28487305 14.57729347
   8.69903971  6.55658171  0.48731866  4.44852876]
 [ 1.95317761 12.98865108 10.6715933   1.48940784  5.24717659 13.92987021
   9.03336791  3.80158128  8.98018407  0.17544958]
 [ 8.59865095 15.6058348   0.82276502  8.46769434  1.74889473 16.24625199
  10.36243782  6.96152421  1.40942569  6.00700757]
 [ 5.05612765  2.54148916  7.33817739  6.43539338 13.90041097  3.44185095
   1.52763649  5.22239606  2.21038729  9.2141147 ]
 [

**80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given
element (pad with a fill value when necessary) (★★★)**

In [137]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 3 2 2 0 8 6 4 9 1]
 [4 3 6 0 0 0 5 5 4 8]
 [3 1 5 7 0 3 9 8 1 8]
 [9 6 0 3 9 3 6 6 7 8]
 [8 2 5 7 4 4 5 9 1 6]
 [4 8 9 5 3 3 0 3 9 1]
 [1 2 2 8 3 7 4 8 1 2]
 [4 2 0 0 4 3 8 1 5 8]
 [2 5 4 7 3 7 4 1 9 2]
 [7 5 0 5 5 9 0 6 3 7]]
[[0 0 0 0 0]
 [0 2 3 2 2]
 [0 4 3 6 0]
 [0 3 1 5 7]
 [0 9 6 0 3]]


/home/rafaelfigueredog/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


**81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6],
..., [11,12,13,14]]? (★★★)**

In [139]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R) # que massa!

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


**82. Compute a matrix rank (★★★)**

In [140]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


**83. How to find the most frequent value in an array?**

In [142]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[2 7 1 9 2 0 6 9 2 6 4 3 7 3 0 1 3 0 7 3 0 1 3 9 5 3 9 5 4 5 1 3 1 0 3 9 6
 2 9 2 2 9 4 7 2 8 5 4 5 1]
3


**84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)**

In [143]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 4 3]
   [4 4 4]
   [0 4 4]]

  [[4 3 1]
   [4 4 3]
   [4 4 0]]

  [[3 1 3]
   [4 3 1]
   [4 0 4]]

  [[1 3 0]
   [3 1 1]
   [0 4 1]]

  [[3 0 4]
   [1 1 3]
   [4 1 1]]

  [[0 4 4]
   [1 3 3]
   [1 1 0]]

  [[4 4 0]
   [3 3 4]
   [1 0 4]]

  [[4 0 1]
   [3 4 0]
   [0 4 0]]]


 [[[4 4 4]
   [0 4 4]
   [0 3 0]]

  [[4 4 3]
   [4 4 0]
   [3 0 4]]

  [[4 3 1]
   [4 0 4]
   [0 4 2]]

  [[3 1 1]
   [0 4 1]
   [4 2 0]]

  [[1 1 3]
   [4 1 1]
   [2 0 4]]

  [[1 3 3]
   [1 1 0]
   [0 4 1]]

  [[3 3 4]
   [1 0 4]
   [4 1 4]]

  [[3 4 0]
   [0 4 0]
   [1 4 2]]]


 [[[0 4 4]
   [0 3 0]
   [3 3 2]]

  [[4 4 0]
   [3 0 4]
   [3 2 3]]

  [[4 0 4]
   [0 4 2]
   [2 3 2]]

  [[0 4 1]
   [4 2 0]
   [3 2 2]]

  [[4 1 1]
   [2 0 4]
   [2 2 4]]

  [[1 1 0]
   [0 4 1]
   [2 4 1]]

  [[1 0 4]
   [4 1 4]
   [4 1 4]]

  [[0 4 0]
   [1 4 2]
   [1 4 4]]]


 [[[0 3 0]
   [3 3 2]
   [2 2 3]]

  [[3 0 4]
   [3 2 3]
   [2 3 1]]

  [[0 4 2]
   [2 3 2]
   [3 1 2]]

  [[4 2 0]
   [3 2 2]
   [1 2 1]]

  [[2 0 4]
   

**85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)**

In [144]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6 10  6 11 11]
 [10  9  7 10 12]
 [ 6  7  9 42  6]
 [11 10 42  0  7]
 [11 12  6  7  2]]


**86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of
of the p matrix products at once? (result has shape (n,1)) (★★★)**

In [145]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


**87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)**

In [146]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


**88. How to implement the Game of Life using numpy arrays? (★★★)**

In [147]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


**89. How to get the n largest values of an array (★★★)**

In [149]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


**90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)**

In [150]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


**91. How to create a record array from a regular array? (★★★)**

In [151]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


**92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)**

In [153]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)
print(x)

4.72 s ± 139 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
326 ms ± 68.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
318 ms ± 34.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
[0.20789502 0.39865087 0.40400346 ... 0.09752201 0.23517916 0.36163048]


**93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of
B regardless of the order of the elements in B? (★★★)**

In [154]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 4 6 7]


**94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)**

In [155]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 2 1]
 [1 4 0]
 [2 1 2]
 [0 2 0]
 [3 2 2]
 [4 1 0]
 [4 4 1]
 [3 3 3]
 [2 2 4]
 [2 2 2]]
[[4 2 1]
 [1 4 0]
 [2 1 2]
 [0 2 0]
 [3 2 2]
 [4 1 0]
 [4 4 1]
 [2 2 4]]
[[4 2 1]
 [1 4 0]
 [2 1 2]
 [0 2 0]
 [3 2 2]
 [4 1 0]
 [4 4 1]
 [2 2 4]]


**95. Convert a vector of ints into a matrix binary representation (★★★)**

In [156]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


**96. Given a two dimensional array, how to extract unique rows? (★★★)**

In [157]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


**97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)**

In [158]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.04031167, 0.02998971, 0.05061932, 0.02327427, 0.04404887,
        0.03445707, 0.02844818, 0.02206715, 0.00648537, 0.02851498],
       [0.59986338, 0.44626608, 0.7532478 , 0.34633598, 0.65547536,
        0.51274329, 0.42332708, 0.32837336, 0.09650639, 0.42432115],
       [0.59906935, 0.44567536, 0.75225074, 0.34587753, 0.65460772,
        0.51206458, 0.42276673, 0.3279387 , 0.09637865, 0.42375948],
       [0.08811637, 0.06555384, 0.11064764, 0.0508747 , 0.09628544,
        0.07531895, 0.06218424, 0.0482361 , 0.01417622, 0.06233026],
       [0.22005428, 0.16370855, 0.27632193, 0.12705012, 0.24045502,
        0.18809509, 0.15529359, 0.1204607 , 0.03540247, 0.15565825],
       [0.35703997, 0.26561853, 0.44833471, 0.20613992, 0.39014035,
        0.30518591, 0.25196519, 0.19544853, 0.05744081, 0.25255686],
       [0.16737135, 0.12451528, 0.21016802, 0.0966332 , 0.18288797,
        0.14306347, 0.11811494, 0.09162135, 0.02692681, 0.1183923 ],
       [0.13113424, 0.09755682, 0.1646651

**98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)**

In [159]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

**99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a
multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)**

In [160]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


**100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an
array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
(★★★)**

In [161]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.12947334  0.19948795]


**OBS:** Algumas respostas não foram criadas por mim. Rodei o código para entender o exercício mesmo assim.

Referências: 

<https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md>