## Métodos Numéricos
#### Rafael Guimarães
#### Sistemas e Equações Lineares

In [6]:
import scipy.linalg as sla
import numpy as np

**Exercício 1.** Verifique, refazendo o exemplo acima, se a equação da substituição retroativa, descrita na equação 20, de fato funciona.

In [7]:
A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
B = np.array([-10, -1, 3, 2])

In [8]:
x = sla.solve_triangular(A,B)

In [9]:
x

array([ 1., -1.,  2.,  1.])

**Exercício 2.** Faça um programa em Python que calcule a solução de um sistema
triangular superior usando substituição retroativa. Para representação das matrizes e
vetores use exclusivamente Numpy

In [56]:
def solveSuperiorLinearEquation(a, b):
    
    n = np.size(b)
    x = np.zeros(n)
    
    for i in range(n-1, -1, -1):
        soma = 0
        for j in range(i+1, n):
            soma += a[i][j]*x[j] 
        
        x[i] = (b[i] - soma)/ a[i][i]
    return x

In [57]:
solveSuperiorLinearEquation(A, B)

array([ 1., -1.,  2.,  1.])

**Exercício 3.** Faça um programa em Python que calcule a solução de um sistema
triangular inferior usando substituição progressiva. Para representação das matrizes e
vetores use exclusivamente Numpy.

In [78]:
def solveInferiorLinearEquation(a, b):
    n = np.size(b)
    x = np.zeros(n)
    for i in range(n):
        soma = 0
        for j in range(n-1, -1, -1):
            soma += a[i][j]*x[j] 
        
        x[i] = (b[i] - soma)/ a[i][i]
    return x

In [79]:
A2 = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b2 = np.array([4, 2, 4, 2])

In [82]:
solveInferiorLinearEquation(A2, b2)

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [87]:
def elimin_gaussiana(a,b,imp = False, norma='inf'):

    import numpy as np #colocadas aqui para evitar problemas de namespace
    import scipy.linalg as sla #colocadas aqui para evitar problemas de namespace
    #matriz estendida Me
    b = np.mat(b).T
    Me = np.concatenate((a,b), axis=1)
    if imp: print('Matriz estendida: \n',Me,'\n\n')
    if imp: print('='*80)
    for j in range(Me.shape[-1] - 2): #coluna
        if imp: print('Operação na coluna', j)
        if imp: print('='*80, '\n\n')
        for i in range(j+1, Me.shape[0]): #linha
            Me[i] = Me[i] - (Me[i,j]/Me[j,j])*Me[j] #operações com cada linha
            if imp: print('Operação na linha', i, ':',Me[i], '\n')
            if imp: print('Matriz escalonando: \n',Me,'\n')
        if imp: print('='*80)
    if imp: print('\nMatriz escalonada: \n',Me,'\n')
    Matriz_A = np.delete(Me, -1, axis=1) #matriz de coeficientes escalonada
    Vetor_b = Me[:,-1] #matriz de termos independentes escalonada
    Vetor_x = sla.solve_triangular(Matriz_A, Vetor_b) # solução do sistema escalona
    if imp: print('='*80,'\n\nSolução do sistema: \n', Vetor_x)
    #verificação do erro do sistema
    if norma is 'inf': norma = np.inf
    if norma is '-inf': norma = -np.inf
    Erro = sla.norm(b - a.dot(Vetor_x),ord = norma)
    return (Matriz_A, Vetor_b, Vetor_x, Erro)


In [88]:
A = np.array([[2, 3, -1], [4, 4, -3], [2, -3, 1]])
b = np.array([5, 3, -1])

In [90]:
elimin_gaussiana(A, b, True)

Matriz estendida: 
 [[ 2  3 -1  5]
 [ 4  4 -3  3]
 [ 2 -3  1 -1]] 


Operação na coluna 0


Operação na linha 1 : [[ 0 -2 -1 -7]] 

Matriz escalonando: 
 [[ 2  3 -1  5]
 [ 0 -2 -1 -7]
 [ 2 -3  1 -1]] 

Operação na linha 2 : [[ 0 -6  2 -6]] 

Matriz escalonando: 
 [[ 2  3 -1  5]
 [ 0 -2 -1 -7]
 [ 0 -6  2 -6]] 

Operação na coluna 1


Operação na linha 2 : [[ 0  0  5 15]] 

Matriz escalonando: 
 [[ 2  3 -1  5]
 [ 0 -2 -1 -7]
 [ 0  0  5 15]] 


Matriz escalonada: 
 [[ 2  3 -1  5]
 [ 0 -2 -1 -7]
 [ 0  0  5 15]] 


Solução do sistema: 
 [[1.]
 [2.]
 [3.]]


(matrix([[ 2,  3, -1],
         [ 0, -2, -1],
         [ 0,  0,  5]]), matrix([[ 5],
         [-7],
         [15]]), array([[1.],
        [2.],
        [3.]]), 0.0)

In [91]:
import numpy as np
import scipy.linalg as sla

In [92]:
a = np.array([[2,3,-1],[4,4,-3],[2,-3,1]])
b = np.array([5,3,-1])
M = elimin_gaussiana(a,b)
M

Matriz estendida: 
 [[ 2  3 -1  5]
 [ 4  4 -3  3]
 [ 2 -3  1 -1]] 


Operação na coluna 0


Operação na linha 1 : [[ 0 -2 -1 -7]] 

Matriz escalonando: 
 [[ 2  3 -1  5]
 [ 0 -2 -1 -7]
 [ 2 -3  1 -1]] 

Operação na linha 2 : [[ 0 -6  2 -6]] 

Matriz escalonando: 
 [[ 2  3 -1  5]
 [ 0 -2 -1 -7]
 [ 0 -6  2 -6]] 

Operação na coluna 1


Operação na linha 2 : [[ 0  0  5 15]] 

Matriz escalonando: 
 [[ 2  3 -1  5]
 [ 0 -2 -1 -7]
 [ 0  0  5 15]] 


Matriz escalonada: 
 [[ 2  3 -1  5]
 [ 0 -2 -1 -7]
 [ 0  0  5 15]] 


Solução do sistema: 
 [[1.]
 [2.]
 [3.]]


(matrix([[ 2,  3, -1],
         [ 0, -2, -1],
         [ 0,  0,  5]]), matrix([[ 5],
         [-7],
         [15]]), array([[1.],
        [2.],
        [3.]]), 0.0)