## Métodos Numéricos
#### Rafael Guimarães
#### Sistemas e Equações Lineares

In [6]:
import scipy.linalg as sla
import numpy as np

**Exercício 1.** Verifique, refazendo o exemplo acima, se a equação da substituição retroativa, descrita na equação 20, de fato funciona.

In [7]:
A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
B = np.array([-10, -1, 3, 2])

In [8]:
x = sla.solve_triangular(A,B)

In [9]:
x

array([ 1., -1.,  2.,  1.])

**Exercício 2.** Faça um programa em Python que calcule a solução de um sistema
triangular superior usando substituição retroativa. Para representação das matrizes e
vetores use exclusivamente Numpy

In [56]:
def solveSuperiorLinearEquation(a, b):
    
    n = np.size(b)
    x = np.zeros(n)
    
    for i in range(n-1, -1, -1):
        soma = 0
        for j in range(i+1, n):
            soma += a[i][j]*x[j] 
        
        x[i] = (b[i] - soma)/ a[i][i]
    return x

In [57]:
solveSuperiorLinearEquation(A, B)

array([ 1., -1.,  2.,  1.])

**Exercício 3.** Faça um programa em Python que calcule a solução de um sistema
triangular inferior usando substituição progressiva. Para representação das matrizes e
vetores use exclusivamente Numpy.

In [78]:
def solveInferiorLinearEquation(a, b):
    n = np.size(b)
    x = np.zeros(n)
    for i in range(n):
        soma = 0
        for j in range(n-1, -1, -1):
            soma += a[i][j]*x[j] 
        
        x[i] = (b[i] - soma)/ a[i][i]
    return x

In [79]:
A2 = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b2 = np.array([4, 2, 4, 2])

In [81]:
solveInferiorLinearEquation(A2, b2)

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])